# Generated by Django 6.1 on 2026-09-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jobposting'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('author_role', models.CharField(blank=True, max_length=150)),
                ('quote', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='qualification',
            field=models.CharField(blank=True, choices=[('none', 'No formal qualification required'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('other', 'Other')], max_length=20),
        ),
    ]
