# Generated by Django 6.1 on 2026-09-08 12:07

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_employeestory_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeestory',
            name='quote',
            field=models.TextField(help_text='Keep to 70 words or fewer — longer quotes will be rejected.', validators=[main.models.validate_quote_length]),
        ),
    ]
