# Generated by Django 6.1 on 2026-09-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_newscategory_newstag_alter_newsarticle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
    ]
