# Generated by Django 6.1 on 2026-09-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_newsarticle_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('item_description', models.CharField(choices=[('manilla_roll', 'Manilla Paper Roll'), ('kraft_roll', 'Kraft Paper Roll'), ('newsprint_roll', 'Newsprint Roll'), ('custom', 'Custom / Other (describe in notes)')], max_length=30)),
                ('color', models.CharField(blank=True, help_text='Leave blank if natural/unspecified', max_length=100)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in metres', max_digits=8)),
                ('gsm', models.PositiveIntegerField(help_text='Paper weight, grams per square metre')),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('rolls', 'Rolls'), ('kg', 'Kilograms'), ('tons', 'Tons')], default='rolls', max_length=10)),
                ('core_diameter', models.CharField(blank=True, help_text='If applicable, e.g. roll core size', max_length=50)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('delivery_location', models.CharField(blank=True, max_length=200)),
                ('preferred_delivery_date', models.DateField(blank=True, null=True)),
                ('lpo_file', models.FileField(blank=True, null=True, upload_to='order_lpos/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('closed', 'Closed')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
