# Generated by Django 6.1 on 2026-09-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_orderrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='core_diameter',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='unit',
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='length',
            field=models.DecimalField(decimal_places=2, help_text='Length in millimetres', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity in kilograms (kg)'),
        ),
    ]
