# Generated by Django 6.1 on 2026-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_orderrequest_core_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='theme_color',
            field=models.CharField(default='#14335c', help_text="Hex color for this product's slide background, e.g. #8b5e3c for brown paper", max_length=7),
        ),
    ]
