# Generated by Django 6.1 on 2026-09-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_image_product_theme_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['category', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('home_hero', 'Homepage Hero Carousel'), ('about_hero', 'About Page Banner'), ('about_story', 'About Page — Our Story'), ('careers_hero', 'Careers Page Banner'), ('order_hero', 'Order Page Banner'), ('general', 'General / Uncategorized')], default='general', max_length=20),
        ),
    ]
