# Generated by Django 6.1 on 2026-09-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_product_options_product_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('home_hero', 'Homepage Hero Carousel'), ('about_hero', 'About Page Banner'), ('about_story', 'About Page — Our Story'), ('careers_hero', 'Careers Page Banner'), ('order_hero', 'Order Page Banner'), ('news_hero', 'News Page Banner'), ('general', 'General / Uncategorized')], default='general', max_length=20),
        ),
    ]
