# Generated by Django 6.1 on 2026-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_leadershipmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='item_description',
            field=models.CharField(max_length=200),
        ),
    ]
