# Generated by Django 6.1 on 2026-09-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_orderrequest_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the order form without deleting')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
            ],
            options={
                'verbose_name': 'Order item option',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
