# Generated by Django 6.1 on 2026-09-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contactmessage_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='client_email_sent',
            field=models.BooleanField(default=False, help_text="Whether the confirmation copy reached the sender's email"),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='client_email_sent',
            field=models.BooleanField(default=False, help_text="Whether the confirmation copy reached the applicant's email"),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='client_email_sent',
            field=models.BooleanField(default=False, help_text="Whether the confirmation copy reached the client's email"),
        ),
    ]
